[package]
name = "sui-tool"
version = "0.6.1"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { version = "1.0.58", features = ["backtrace"] }
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.35"
clap = { version = "3.1.17", features = ["derive"] }
telemetry-subscribers = { git = "https://github.com/MystenLabs/mysten-infra", rev = "123c9e40b529315e1c1d91a54fb717111c3e349c" }
mysten-network = { git = "https://github.com/MystenLabs/mysten-infra", rev = "123c9e40b529315e1c1d91a54fb717111c3e349c" }
textwrap = "0.15"
futures = "0.3.21"
rocksdb = "0.18.0"
typed-store = { git = "https://github.com/MystenLabs/mysten-infra", rev = "123c9e40b529315e1c1d91a54fb717111c3e349c"}
tempfile = "3.3.0"
narwhal-executor = { git = "https://github.com/MystenLabs/narwhal", rev = "d67e27d33b8515f919f45694660fceb20db626c4", package = "executor" }
serde_with = { version = "1.14.0", features = ["hex"] }
sui-storage = { path = "../sui-storage" }
serde = { version = "1.0.140", features = ["derive"] }

sui-core = { path = "../sui-core" }
sui-config = { path = "../sui-config" }
sui-types = { path = "../sui-types" }

colored = "2.0.0"
workspace-hack = { path = "../workspace-hack"}
